# docker-compose.yml
version: '3.8'

services:
  app:
    build: .
    # Ánh xạ cổng ứng dụng: 6080 trên máy chủ được ánh xạ tới 6080 trong container.
    ports:
      - "6080:6080"
    # Đảm bảo dịch vụ 'db' khởi động trước dịch vụ 'app'
    depends_on:
      - db
    # Định nghĩa các biến môi trường để kết nối với cơ sở dữ liệu
    environment:
      # QUAN TRỌNG: Thay đổi serverTimezone từ UTC thành Asia/Ho_Chi_Minh
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/training3?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""
      # Đặt port cho ứng dụng
      SERVER_PORT: 6080
      # ĐẶT MÚI GIỜ CHẠY CHO DỊCH VỤ APP.
      TZ: Asia/Ho_Chi_Minh

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: training3
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      TZ: Asia/Ho_Chi_Minh
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-time-zone=Asia/Ho_Chi_Minh

  # Dịch vụ mới: phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    # Ánh xạ cổng: Bạn có thể truy cập phpMyAdmin tại http://localhost:8081
    ports:
      - "8081:80"
    depends_on:
      - db
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ""
    volumes:
      - phpmyadmin_session:/sessions

# Định nghĩa các volume được sử dụng
volumes:
  mysql_data:
  phpmyadmin_session:
